// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3Ui4CokDs4KdkAm1tU7tBluHZ6X_kYZM',
    appId: '1:858113659886:web:3bf38f952069480b8974ff',
    messagingSenderId: '858113659886',
    projectId: 'she-1acd0',
    authDomain: 'she-1acd0.firebaseapp.com',
    storageBucket: 'she-1acd0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7rLnfVqZcW9R2Wb8ycj9ML6Yu7Nyv3VA',
    appId: '1:858113659886:android:68ad40ee5c6860948974ff',
    messagingSenderId: '858113659886',
    projectId: 'she-1acd0',
    storageBucket: 'she-1acd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKiSy6MQ8v3-i0yapSYGPPYSDAMnticKA',
    appId: '1:858113659886:ios:2b247684611e884e8974ff',
    messagingSenderId: '858113659886',
    projectId: 'she-1acd0',
    storageBucket: 'she-1acd0.appspot.com',
    iosBundleId: 'com.example.SceureMeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKiSy6MQ8v3-i0yapSYGPPYSDAMnticKA',
    appId: '1:858113659886:ios:cba11b0fa1d432da8974ff',
    messagingSenderId: '858113659886',
    projectId: 'she-1acd0',
    storageBucket: 'she-1acd0.appspot.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
